- name: simple condition
  hosts: localhost
  vars:
    NAME: DevOps
  tasks:
  - name: run this name is DevOps
    ansible.builtin.debug:
      msg: "hellow {{NAME}}"
    when : NAME == "DevOps" #if this expression is true then only this module will run
