- name: install multiple packages  : #we can use for loop
  hosts: mongodb
  become: yes
  tasks:
  - name: install multipackages
    ansible.builtin.yum: # command to install
      name: "{{item}}"
      state: installed
      #list of strings
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx