- name: variables in ansible
  hosts: mongodb
  #this is play vevel cariables, map
  vars:
   COURSE: devops with aws
   TRAINER: kirankumar
   DURATION: 110 hrs
  tasks:
  - name: print hellow world
    ansible.builtin.debug:
      msg: "Hellow, iam learning ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hellow, I'am learning {{COURSE}}, trainer {{TRAINER}} and duration is {{DURATION}}"
    