- name: varibales from files
  hosts: localhost #managing the ansible server itself
  vars_files:
  - samplevars.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "we are learning {{NAME}}, duration is {{DURATION}}, and trainer is {{TRAINER}}"