- name: variables from files
  hosts: mongodb #managing the ansible server itself
  vars_files:
  - variables.yaml
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Hellow, I'am learning {{NAME}}, trainer {{TRAINER}} and duration is {{DURATION}}"