- name: variables from files
  hosts: mongodb #managing the ansible server itself
  vars_files:
  - samplevars.yaml
  tasks:
  - name: print vars
    ansible.builtin.debug:
      msg: "We are learning {{NAME}}, Duration is: {{DURATION}}, and Trainer is: {{TRAINER}}"